---
title: "SDS 192 Mini-Project 1 Standards"
subtitle: "SDS 192"
author: 
- name: "Tabitha Githinji"
  affiliation: Smith College
- name: "Ayla Hauser"
  affiliation: Smith College
- name: Author Three
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
source:
  mode: editor
output: 
  html_document:
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---


# Understanding Datasets

We were able to interpret the data set, allowing us to form a specific question relating to the data that we wanted to study. Our graphs and blog post demonstrate that we understood the meaning of each variable and were able to distinguish which variables were the best for our research question. The blog post displays our ability to understand the ethics and provenance of the data set by explaining where the data is coming from and what is implied by its origin. 

# Visualization Aesthetics

Our graphs correlate with the correct data type for our variables and research question, highlighting our ability to plot variables on appropriate map aesthetics. We adjusted our scales to be organized and understandable by adding jitter, binwidth, color, and alpha arguments. When addressing overplotting, we used data wrangling and jitter to spread out the data and get rid of unhelpful values. 

# Plotting Frequencies and Distributions

We answered our specific research question by plotting the correlating statistical information. This allowed our data to be visualized in an organized, accessible way. We added titles, captions, x-axis labels, and y-axis labels to add clarity and context to our plots. In our blog post, we concluded that there are drastic differences in admission rates and cost of attendance for private and public universities. Our blog post correctly summarizes and expands upon the research question findings we represented in our plots. 

