website:
  title: "Portfolio Showcase"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

  sidebar:
    top:
      - href: projects/scorecard_analysis.qmd
        text: Scorecard Analysis

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual
