website:
  title: "Tabitha Githinji's Portfolio"
  output dir: docs
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

  sidebar:
    top:
      - href: project-1-alya-tabitha/scorecard_analysis.qmd
        text: Scorecard Analysis
      - href: project-2-fec-alya-tabitha/fec-analysis.qmd
        text: FEC Analysis
      - href: project-3-mapping-sabzara-tabitha/mapping.qmd
        text: Mapping Demographics

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

