---
title: "SDS 192 Mini-Project 2 Standards"
subtitle: "SDS 192"
author: 
- name: Ayla Hauser
  affiliation: Smith College
- name: Tabitha Githinji
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
source:
  mode: editor
output: 
  html_document:
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---


# Transforming Data

we filtered the data to confine it to Ma state and Boston City then selected the variables we needed to check and then summarized to calculate the amount of contributions the candidates were gaining.

# Joining Data

Joined the Results_senate and campaigns tables, using inner_join, to be able to compare the total amount of money disbursed by senators during their campaign and check whether they eon or lost in the elections.

# GitHub

On GitHub, we delegated tasks using issues, assigning each team member specific responsibilities. We worked across multiple branches, merging and creating pull requests to the main branch once code was reviewed. Collaborating this way allowed us to review each other's code, ensuring accuracy and cohesion across our work.

